apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: prometheus
  labels:
    app: prometheus
    component: server
    release: prometheus
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: server
    release: prometheus
  type: NodePort
