apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager
  namespace: prometheus
  labels:
    app: prometheus
    component: alertmanager
    release: prometheus
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: prometheus
    component: alertmanager
    release: prometheus
  type: NodePort
