apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: prometheus
  labels:
    app: prometheus
    component: blackbox-exporter
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
      component: blackbox-exporter
      release: prometheus
  template:
    metadata:
      labels:
        app: prometheus
        component: blackbox-exporter
        release: prometheus
       
    spec:
      containers:
      - args:
        - --config.file=/etc/blackbox_exporter/blackbox.yml
        - --log.level=info
        - --web.listen-address=:9115
        image: prom/blackbox-exporter
        imagePullPolicy: IfNotPresent
        name: blackbox-exporter
        ports:
        - containerPort: 9115
          name: blackbox-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9115
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /etc/blackbox_exporter
          name: config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: blackbox-exporter
        name: config

