apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: prometheus
  labels:
    app: prometheus
    component: blackbox-exporter
    release: prometheus
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 9115
    protocol: TCP
    targetPort: 9115
  selector:
    app: prometheus
    component: blackbox-exporter
    release: prometheus
  type: NodePort
