apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
  namespace: prometheus
  labels:
    app: prometheus
    component: node-exporter
    release: prometheus
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: prometheus
    component: node-exporter
    release: prometheus
  sessionAffinity: None
  type: ClusterIP
