apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  nfs:
    server: 192.168.10.40
    path: /data/nfs
  accessModes: 
  - ReadWriteMany
  capacity:  
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc 
  namespace: jenkins
spec:
  accessModes: 
  - ReadWriteMany
  resources:  
    requests:
      storage: 10Gi
  volumeName: jenkins-pv
  
